use_frameworks!

platform :ios, '10.0'

target 'testxcode14_Example' do
  pod 'testxcode14', :path => '../'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'IQKeyboardManager', '6.5.9'
  pod "Aspects"
  target 'testxcode14_Tests' do
    inherit! :search_paths

    
  end
end
